# -*- coding: utf-8 -*-
"""código incorreto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s_WiBIR1aRj_ok1AOci3kdp5ehBg8J5O
"""

int main() {
    setlocale(LC_ALL, "Portuguese");
//Definindo as variáveis:
    int numero_de_tentativas = 0;
    int chute = 0;
    int numero_aleatorio;
    int i;

//Gerando o número aleatório:
    srand(time(NULL));
    numero_aleatorio = rand() % 100;

//Iniciando Contador:
    for (i = 0; i < 100; i++) {
        printf("Digite um número: ");
        scanf("%d", &chute);

//Conta as tentativas:
        numero_de_tentativas+=1;

//Condicionais:
        if (chute > numero_aleatorio) {
            printf("Número muito alto!\n");
        } else if (chute < numero_aleatorio) {
            printf("Número muito baixo!\n");
        } else {
            printf("Parabéns! Você acertou o número correto em %d tentativas.\n", numero_de_tentativas);

//Encerra o loop:
            break;
        }
    }

    return 0;
}