# -*- coding: utf-8 -*-
"""código incorreto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s_WiBIR1aRj_ok1AOci3kdp5ehBg8J5O
"""

t_termo = int(input("Informe o terceiro termo da PA: "))
razão = int(input("Informe a razão: "))
n = int(input("Informe o número de termos a serem descobertos, o valor deve ser maior que 3: "))
contador = 0
while n<=3:
  n = int(input("Informe o número de termos a serem descobertos, o valor deve ser maior que 3: "))
print("\nSegue o desenvolvimento da PA: ")
print(t_termo - (2*razão))
print(t_termo - razão)
  contador += 1
  PA = t_termo + (contador - 1) * razão
  print(PA)